spring:
  application:
    name: organization

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource:
    url: jdbc:h2:mem:demo
    #    url: jdbc:h2:~/demo #User folder
    #    url: jdbc:h2:file:./demo_db #Specific folder
    driver-class-name: org.h2.Driver

  #  datasource:
  #    url: jdbc:mariadb://${db.host}:3306/troubleshooting?createDatabaseIfNotExist=true
  #    username: root
  #    password: root

  flyway:
    enabled: false

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop
      #      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  h2:
    console:
      enabled: true
      path: /h2-console




server:
  servlet:
    contextPath: /
  port: 8092


